### ISSUE TITLE
Add additional aliases for set symbols

### ISSUE THREAD

**Issue by jninnes** [jninnes/mtgicons#9]
Allow expansion symbols to be referenced by the set code as well as the name, eg.

    <i class="mtg champions-of-kamigawa"></i>
    
    <i class="mtg chk"></i>

**Comment by bra1n** [comment]
I went ahead and added the Gatherer expansion codes to each set, with an "e-" prefix.
Example: `<i class="mtg e-ktk"></i>`
BTW, if you would be willing to change the syntax to something like `class="mtg set ktk"` instead, you could optimize the CSS even further, because all the set icons share at least the colors.

**Comment by jninnes** [comment]
Is there a reason we need to prefix with e- ?

**Comment by bra1n** [comment]
To avoid potential naming conflicts and have a unified naming schema (e=expansion). Though I also think that having "mtg set ktk" would be better than "mtg e-ktk".

**Comment by jninnes** [comment]
Yeah I like "mtg set ktk " better too.

**Comment by bra1n** [comment]
Oh, I just remembered that CSS class names must not start with a digit, so you *have* to prefix them, otherwise you can't support set codes like 5DN (Fifth Dawn) or 1E (Alpha). My suggestion would be "mtg set-ktk" then, if you don't like the "e-". :smile:

**Comment by jninnes** [comment]
Ah, good point. On second thoughts, let's stick with e-
